---
- name: Check if yay exists
  stat:
    path: /usr/bin/yay
  register: yay_stat

- name: Pull yay AUR package
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: /home/vagrant/yay
  when: not yay_stat.stat.exists

- name: Build and install yay
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/yay
  when: not yay_stat.stat.exists

- name: Install yay from AUR using yay (for updates)
  command: yay --noconfirm --noeditmenu -S yay
  when: not yay_stat.stat.exists
