---
- name: Read current time zone
  shell: cat /etc/timezone
  changed_when: false
  register: current_time_zone

- name: Set the time zone
  shell: timedatectl set-timezone '{{ desired_time_zone }}'
  when: current_time_zone.stdout != desired_time_zone

- name: Setup time sync settings
  template:
    src: etc-systemd--timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0440
    backup: yes

- name: Start and enable the time sync service
  service:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
