---
# This first part just replicates what was done in the base install script
# The exception is the SSH role.  It can potentially lock you out of a machine
# by a misconfigured SSH config so it is run here.  If it causes issuse in this
# main script it can be removed.
- name: Core setup (bootstrap)
  hosts: all
  become: true
  vars_files:
    - vars/core.yml
  roles:
    - hostname
    - pacman-config
    - install-applications
#    - bootloader-config
    - sudo
    - ansible-user
    - vagrant-user
    - keymap
    - time
    - locale
    - ssh

#- name: Common setup
#  hosts: all
#  become: true
#  roles:
    # - systemd
    # - network
    # - security
    # - audio ??
    # - printer-install
    # - install-dev-frameworks

# - name: X11 Desktop Setup
#   hosts: all
#   roles:
#     - desktop-kde
#     - desktop-addon-i3
#     - { role: virtualbox-guest, when: ansible_virtualization_type == "virtualbox" and ansible_virtualization_role == "guest" }

# - name: Install Fonts
#   hosts: all
#   vars_files:
#     - vars/fonts.yml
#   roles:
#     - install-nerdfonts
#     - install-fonts

# - name: Desktop Workstation Applications
#   hosts: all
#   vars:
#     package_set: "Shared Applications"
#   vars_files:
#     - vars/shared-applications.yml
#   roles:
#     - install-applications

# - name: VM Applications
#   hosts: desktop_workstations:laptop_workstations:gaming_workstations
#   vars:
#     package_set: "VM Applications"
#   vars_files:
#     - vars/vm-applications.yml
#   roles:
#     - { role: install-applications, when: ansible_virtualization_role != "guest" }

# - name: Development Applications
#   hosts: desktop_workstations:laptop_workstations:gaming_workstations
#   vars:
#     package_set: "VM Applications"
#   vars_files:
#     - vars/vm-applications.yml
#   roles:
#     - install-applications
