---
# This first part just replicates what was done in the base install script
# The exception is the SSH role.  It can potentially lock you out of a machine
# by a misconfigured SSH config so it is run here.  If it causes issuse in this
# main script it can be removed.
- name: Bootstrap setup
  hosts: all
  become: true
  vars_files:
    - vars/bootstrap.yml
  roles:
    - hostname
    - pacman-config
    - install-applications
    - bootloader-config
    - sudo
    - ansible-user
    - vagrant-user
    - keymap
    - time
    - locale
    - ssh

- name: Aurman
  hosts: all
  become: false
  roles:
    - aurman

- name: Common setup
  hosts: all
  become: true
  roles:
    - role: virtualbox-guest
      when: ansible_virtualization_type == "virtualbox"
            and ansible_virtualization_role == "guest"
    - pacman
    - setup-users
    - video-drivers
    # - systemd
    # - network
    # - security
    # - audio ??
    # - printer-install
    # - install-dev-frameworks

- name: Console Tools
  hosts: all
  become: true
  vars_files:
    - vars/console-tools.yml
  roles:
    - install-applications

- name: X11 Desktop Setup
  hosts: all
  become: true
  roles:
    - desktop-environment

- name: Desktop Applications
  hosts: all
  become: true
  vars_files:
    - vars/desktop-apps.yml
  roles:
    - install-applications

# - name: Install Fonts
#   hosts: all
#   vars_files:
#     - vars/fonts.yml
#   roles:
#     - install-nerdfonts
#     - install-fonts

- name: VM Applications
  hosts: all
  become: true
  vars_files:
    - vars/vm-applications.yml
  roles:
    - role: install-applications
      when: ansible_virtualization_role != "guest"
