---
- name: Checking for vagrant...
  stat:
    path: "/etc/vagrant_box_build_time"
  register: is_vagrant

- name: Add Vagrant user to the VirtualBox group
  user:
    name: "vagrant"
    groups: "vboxsf"
    append: true
  when: is_vagrant.stat.exists

- name: Add Ansible user to the VirtualBox group
  user:
    name: "ansible"
    groups: "vboxsf"
    append: true

- name: Install VirtualBox Utils
  pacman:
    name:
      - xf86-video-vmware
      - virtualbox-guest-utils
      - virtualbox-guest-dkms
    state: present

- name: Install drivers from AUR
  become: false
  yay:
    name: "{{ item }}"
    state: present
  with_items:
    - aic94xx-firmware
    - wd719x-firmware
  notify: Rebuild mkinitcpio

- name: Copy startup.nsh
  copy:
    src: boot-efi--startup.nsh
    dest: /boot/efi/startup.nsh
    owner: root
    group: root
    mode: 0755
    backup: false

- name: Enable VirtualBox Service
  service:
    name: vboxservice.service
    state: started
    enabled: true
