---
- name: Install xorg server
  pacman:
    name:
      - xorg-server
      - mesa
      - libglvnd
      - xorg-xinput
      - xorg-xkill
      - xorg-server-xwayland
      - xorg-xinit
      - xorg-xrandr
      - xterm
    state: present

- name: Install KDE
  pacman:
    name:
      - phonon-qt5-gstreamer
      - libx264
      - plasma-meta
      - plasma-wayland-session
      - kdebase-meta
      - kdeutils-meta
      - dolphin-plugins
      - kde-gtk-config
    state: present

- name: Enable SDDM
  service:
    name: sddm.service
    enabled: true

#- name: Set SDDM config
#  template:
#    src: etc--sddm.conf.j2
#    dest: /etc/sddm.conf
#    owner: root
#    group: root
#    mode: 0644
#    backup: true

- name: Install i3
  pacman:
    name:
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
      - dmenu
      - rofi
    state: present

- name: Install Theme Assets
  pacman:
    name:
      - arc-gtk-theme
      - arc-kde
      - adapta-gtk-theme
      - adapta-kde
      - papirus-icon-theme
      # - kvantum-theme-arc
      # - kvantum-theme-adapta
      - arc-icon-theme
      - gnome-themes-extra
      - gnome-icon-theme
      - gnome-icon-theme-symbolic
      - gnome-icon-theme-extras
      - capitaine-cursors
    state: present

#- name: Install AUR KCM's
#  become: false
#  aurman:
#    name:
#      - systemd-kcm
#    state: present

- name: Install Theme Assets (AUR)
  become: false
  yay:
    name: "{{ item }}"
    state: present
  with_items:
    - numix-cursor-theme-git
    - numix-gtk-theme-git
    - numix-kde-theme-git
    - numix-icon-theme-git
    - numix-circle-icon-theme-git
    - numix-square-icon-theme-git
    - numix-folders-git # not working
