---
- name: Install xorg server
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - libglvnd
    - mesa
    - xorg-server
    - xorg-xinput
    - xorg-xkill
    - xorg-server-xwayland
    - xorg-xinit

- name: Install KDE
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - phonon-qt5-gstreamer
    - libx264
    - plasma
    - kf5
    - plasma-wayland-session
    - ark
    - dolphin
    - dolphin-plugins
    - kate
    - kcalc
    - konsole
    - kwalletmanager

- name: Install SDDM
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - sddm
    - sddm-kcm

- name: Enable SDDM
  service:
    name: sddm.service
    enabled: yes

- name: Set SDDM config
  template:
    src: etc--sddm.conf.j2
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Install i3
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-gaps
    - i3blocks
    - i3lock
    - i3status
    - dmenu
    - rofi

- name: Install Theme Assets
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - arc-gtk-theme
    - arc-kde
    - papirus-icon-theme

- name: Install Theme Assets (AUR)
  become: false
  aurman:
    name: "{{ item }}"
    state: present
  with_items:
    - numix-icon-theme-git
    - numix-folders-git
    - numix-circle-icon-theme-git
    - numix-square-icon-theme-git
    - capitaine-cursors
    - capitaine-cursors-hidpi

