---
- name: Install Printer Drivers And Utilities
  pacman:
    name:
      - cups
      - cups-pdf
      - foomatic-db
      - foomatic-db-engine
      - foomatic-db-nonfree
      - foomatic-db-ppds
      - foomatic-db-gutenprint-ppds
      - foomatic-db-nonfree-ppds
    state: present

- name: Enable the Cups socket
  service:
    name: org.cups.cupsd.socket
    enabled: true
