---
- name: Install pacman packages ({{ package_set }})
  pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: Install aur packages ({{ package_set }})
  yay:
    name: "{{ item }}"
    state: present
  with_items: "{{ aur_packages }}"
