---
- name: Install pacman packages ({{ package_set }})
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ pacman_packages }}"

- name: Install aur packages ({{ package_set }})
  aurman:
    name: "{{ item }}"
    state: present
  with_items: "{{ aur_packages }}"

