---
- name: refresh pacman mirrors
  pacman:
    update_cache: yes

- name: restart paccache
  service:
    name: paccache.timer
    state: restarted

- name: reload systemd config
  command: systemctl daemon-reload

