---
- name: Install Intel Drivers
  pacman:
    name: "{{ item }}"
    state: present
    with_items:
      - xf86-video-intel
      - mesa
      - lib32-mesa
      - libvdpau-va-gl
      - lib32-libvdpau
      - vulkan-intel
      - lib32-vulkan-intel

- name: Install Intel profile script
  template:
    src: etc-profile.d--vdpau-driver.sh.j2
    dest: /etc/profile.d/vdpau-driver.sh
    owner: root
    group: root
    mode: 0755
    backup: true
