---
# For now, I install these on every machine
- name: Primary video drivers
  pacman:
    name:
      - xf86-video-vesa
      - xf86-video-intel
      - xf86-video-amdgpu
      - xf86-video-nouveau
      - xf86-video-vmware
      - mesa
      - vulkan-intel
      - vulkan-radeon
      - libva-mesa-driver
      - libva-intel-driver
      - libva-utils
      - mesa-vdpau
      - libva-vdpau-driver
      - libvdpau-va-gl
      - vdpauinfo
      - libxss
      - vulkan-mesa-layer
      - intel-media-driver
      - intel-media-sdk
      - intel-compute-runtime
      - glu
    state: present
#TODO: Build out a laptop one that uses PRIME for both the NVIDIA (proprietary) and
# Intel graphics drivers at the same time.  Only on machines with both graphics cards.
