---
- name: Determine Number Of Video Cards
  shell: lspci | grep VGA | wc -l
  register: vidCount
  changed_when: false

- name: Determine Video Card Manufacturer
  shell: lspci | grep VGA | tr "[:upper:]" "[:lower:]"
  register: vidCard
  changed_when: false

  # For now, I only install the Intel drivers in single card mode
- include: intel-video.yml
  when: vidCount.stdout != "1"

- include: nvidia-video-nouveau.yml
  when: vidCount.stdout == "1" and vidCard.stdout.find("nvidia") != -1

- include: intel-video.yml
  when: vidCount.stdout == "1"
    and vidCard.stdout.find("intel corporation") != -1
