---
- name: Determine Number Of Video Cards
  shell: lspci | grep VGA | wc -l
  register: vidCount
  changed_when: false

- name: Determine Video Card Manufacturer
  shell: lspci | grep VGA | tr "[:upper:]" "[:lower:]"
  register: vidCard
  changed_when: false

# For now, I install these on every machine
- name: Primary video drivers
  pacman:
    name:
      - xf86-video-intel
      - xf86-video-amdgpu
      - xf86-video-nouveau
      - mesa
      - vulkan-intel
      - vulkan-radeon
      - libva-mesa-driver
      - libva-intel-driver
      - libva-utils
      - mesa-vdpau
      - libva-vdpau-driver
      - libvdpau-va-gl
      - vdpauinfo
      - libxss
      - vulkan-mesa-layer
      - intel-media-driver
    state: present
#TODO: Build out a laptop one that uses PRIME for both the NVIDIA (proprietary) and
# Intel graphics drivers at the same time.  Only on machines with both graphics cards.
